---

- name: 'Start the Leanlabs Kanban redis container'
  docker_container:
    image: "leanlabs/redis:1.0.0"
    name: "kanban_redis"

- name: 'Start the Leanlabs Kanban docker container'
  docker_container:
    image: "leanlabs/kanban:{{ leanlabs_kanban_image_tag }}"
    name: "kanban"
    state: 'started'
    restart_policy: 'always'
    env:
      KANBAN_SERVER_HOSTNAME: "{{ leanlabs_kanban_server_hostname }}"
      KANBAN_GITLAB_URL: 'https://gitlab.com'
      KANBAN_REDIS_ADDR: "kanban_redis:6379"
      KANBAN_ENABLE_SIGNUP: "{{ leanlabs_kanban_signup }}"
      KANBAN_GITLAB_CLIENT: "{{ leanlabs_kanban_gitlab_client | default(omit) }}"
      KANBAN_GITLAB_SECRET: "{{ leanlabs_kanban_gitlab_secret | default(omit) }}"
    links:
      "kanban_redis:kanban_redis"
    log_driver: json-file
    ports:
#      - "127.0.0.1:8000:80"
      - "{% if leanlabs_kanban_listen_ip != '' %}{{ leanlabs_kanban_listen_ip + ':' }}{% endif %}{{ leanlabs_kanban_port }}:80"
